#!/usr/bin/env ruby

require_relative './lib/client'

FILENAME   = '.world.teapot.yaml'.freeze
USE_COLORS = true

begin
  require 'colorize'
  raise LoadError unless USE_COLORS # black and white mode

  PROMPT   = '∴ '.yellow
  RESPONSE = '» '.yellow
  ERROR    = '! '.red
rescue LoadError
  PROMPT   = '∴ '.freeze
  RESPONSE = '» '.freeze
  ERROR    = '! '.freeze
end

conn = Paradise::Client::LocalConnection.new nil, FILENAME
client = Paradise::Client.new conn

$stdout.print PROMPT

begin
  $stdin.each_line do |line|
    result = client.query line

    if result.fetch(:error, false)
      $stdout.print ERROR
    else
      $stdout.print RESPONSE
    end
    $stdout.print result[:text]

    $stdout.print "\n"
    $stdout.print PROMPT
  end
rescue Interrupt
  client.disconnect
ensure
  puts
end
