#!/usr/bin/env ruby

require 'colorize'
require_relative './lib/server'

filename = '.world.teapot.yaml'

world = if File.exist? filename
          Paradise::World.load File.open(filename, 'r')
        else
          Paradise::World.default
        end

server = Paradise::Server.new world
vessel = 0

$stdout.print '∴ '.yellow

begin
  $stdin.each_line do |line|
    $stdout.print '» '.yellow

    result = server.query vessel, line
    $stdout.print result

    $stdout.print "\n∴ ".yellow
  end
rescue Interrupt
  puts "\nSaving world..."
  File.open(filename, 'w') do |f|
    server.world.dump f
  end
  $stdout.print 'Saved'
ensure
  puts
end
