#!/usr/bin/env ruby

require 'colorize'
require_relative './lib/server'

world = Paradise::World.new [
  # The default user
  { name: 'ghost', parent: 1, owner: 0,
    note: 'Well, well, hello there.' },
  # The paradox
  { name: 'library', parent: 1, owner: 1,
    note: 'Hello @(vessel self "name"), and welcome to the ' \
          '@(cc (vessel parent "name")), the stem to an empty world. ' \
          'Type "@(format "learn")" to get started' },
  # A bookshelf
  { name: 'bookshelf', parent: 1, owner: 0 },
  # A desk
  { name: 'desk', attr: 'panelled', parent: 1, owner: 0 }
]

server = Paradise::Server.new world
vessel = 0

$stdout.print '∴ '.yellow

begin
  $stdin.each_line do |line|
    $stdout.print '» '.yellow
    pid = fork do
      server.query vessel, line
    end

    Process.wait pid
    $stdout.print "\n∴ ".yellow
  end
rescue Interrupt
  $stdout.print "\nSaving world..."
ensure
  puts
end
